dataGenome: "data/genome"
genomeURL: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/013/425/GCF_000013425.1_ASM1342v1/GCF_000013425.1_ASM1342v1_genomic.fna.gz"
dataFastq: "data/fastq"
dataTrimmed: "data/trimmed"
dataMapped: "data/mapped"

threads: 4

sra_accessions:
  - SRR10379721
  - SRR10379722
  - SRR10379723
  - SRR10379724
  - SRR10379725
  - SRR10379726
